[build]
builder = "NIXPACKS"

[[services]]
name = "ubereats-backend"
rootDir = "restaurant-recommendation-system"
startCommand = "gunicorn api.app:app"
installCommand = "pip install -r requirements.txt"
port = 5000

[[services]]
name = "ubereats-frontend"
rootDir = "ubereats-frontend"
installCommand = "npm install && npm run build"
startCommand = ""
staticPublishPath = "build"
