services:
  - type: web
    name: uber-eats-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn api.app:app"
    rootDir: restaurant-recommendation-system
    plan: free

  - type: web
    name: uber-eats-frontend
    env: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: build
    rootDir: ubereats-frontend
    plan: free

